/* GENERATED BY TYPECHAIN VER. 0.1.4 */
/* tslint:disable */

import { BigNumber } from 'bignumber.js'
import {
  TypeChainContract,
  promisify,
  ITxParams,
  IPayableTxParams,
  DeferredTransactionWrapper,
} from './typechain-runtime'

export class IRoleRegistry extends TypeChainContract {
  public readonly rawWeb3Contract: any

  public constructor(web3: any, address: string | BigNumber) {
    const abi = [
      {
        anonymous: false,
        inputs: [{ indexed: false, name: '_address', type: 'address' }],
        name: 'Designated',
        type: 'event',
      },
      {
        anonymous: false,
        inputs: [{ indexed: false, name: '_address', type: 'address' }],
        name: 'Discharged',
        type: 'event',
      },
      {
        anonymous: false,
        inputs: [{ indexed: false, name: '_address', type: 'address' }],
        name: 'RoleRegistryCreated',
        type: 'event',
      },
      {
        constant: true,
        inputs: [{ name: '_address', type: 'address' }],
        name: 'hasRole',
        outputs: [{ name: 'hasTheRole', type: 'bool' }],
        payable: false,
        stateMutability: 'view',
        type: 'function',
      },
      {
        constant: false,
        inputs: [{ name: '_address', type: 'address' }],
        name: 'designate',
        outputs: [],
        payable: false,
        stateMutability: 'nonpayable',
        type: 'function',
      },
      {
        constant: false,
        inputs: [{ name: '_address', type: 'address' }],
        name: 'discharge',
        outputs: [],
        payable: false,
        stateMutability: 'nonpayable',
        type: 'function',
      },
    ]
    super(web3, address, abi)
  }

  static async createAndValidate(
    web3: any,
    address: string | BigNumber
  ): Promise<IRoleRegistry> {
    const contract = new IRoleRegistry(web3, address)
    const code = await promisify(web3.eth.getCode, [address])
    if (code === '0x0') {
      throw new Error(`Contract at ${address} doesn't exist!`)
    }
    return contract
  }

  public hasRole(_address: BigNumber | string): Promise<boolean> {
    return promisify(this.rawWeb3Contract.hasRole, [_address.toString()])
  }

  public designateTx(
    _address: BigNumber | string
  ): DeferredTransactionWrapper<ITxParams> {
    return new DeferredTransactionWrapper<ITxParams>(this, 'designate', [
      _address.toString(),
    ])
  }
  public dischargeTx(
    _address: BigNumber | string
  ): DeferredTransactionWrapper<ITxParams> {
    return new DeferredTransactionWrapper<ITxParams>(this, 'discharge', [
      _address.toString(),
    ])
  }
}
